package com.triplived.entity;

// Generated Mar 28, 2015 8:38:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "trip")
public class CityDb implements java.io.Serializable {

	private String cityCode;
	private String cityCodeTl;
	private CountryDb countryDb;
	private String state;
	private String status;
	private String chtAltitude;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String cityname;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	
	private String cityDescription; 
	//private Set<Attraction> attractions = new HashSet<Attraction>(0);
	

	@Column(name = "DESCRIPTION", length = Integer.MAX_VALUE)
	public String getCityDescription() {
		return cityDescription;
	}

	public void setCityDescription(String cityDescription) {
		this.cityDescription = cityDescription;
	}

	public CityDb() {
	}

	public CityDb(String cityCode, CountryDb countryDb, String cityname,
			String createdBy, Date createdDate) {
		this.cityCode = cityCode;
		this.countryDb = countryDb;
		this.cityname = cityname;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public CityDb(String cityCode, CountryDb countryDb, String status,
			String chtAltitude, BigDecimal latitude, BigDecimal longitude,
			String cityname, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate) {
		this.cityCode = cityCode;
		this.countryDb = countryDb;
		this.status = status;
		this.chtAltitude = chtAltitude;
		this.latitude = latitude;
		this.longitude = longitude;
		this.cityname = cityname;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		//this.attractions = attractions;
	}

	@Id
	@Column(name = "CITY_CODE", unique = true, nullable = false, length = 20)
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "CITY_CODE_TL", unique = true, nullable = false, length = 20)
	public String getCityCodeTl() {
		return cityCodeTl;
	}

	public void setCityCodeTl(String cityCodeTl) {
		this.cityCodeTl = cityCodeTl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE", nullable = false)
	public CountryDb getCountry() {
		return this.countryDb;
	}

	public void setCountry(CountryDb countryDb) {
		this.countryDb = countryDb;
	}

	@Column(name = "STATE", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CHT_ALTITUDE", length = 65535)
	public String getChtAltitude() {
		return this.chtAltitude;
	}

	public void setChtAltitude(String chtAltitude) {
		this.chtAltitude = chtAltitude;
	}

	@Column(name = "LATITUDE", precision = 9, scale = 6)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 9, scale = 6)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "CITYNAME", nullable = false, length = 100)
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 60)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", length = 60)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Attraction> getAttractions() {
		return this.attractions;
	}

	public void setAttractions(Set<Attraction> attractions) {
		this.attractions = attractions;
	}*/

}
