package com.triplived.entity;

// Generated Mar 28, 2015 8:38:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.gcm.GCMNotificationStatus;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "message_details", catalog = "trip")
public class MessageDetailsDb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name="ID")
    @GeneratedValue
	private Long id;
	
	
	@Column(name="REG_ID")
	private String registrationId;
	
	@Column(name="MESSAGE_ID")
	private String messageId;
	
	
	@Column(name="CREATED_DATE")
	private Date createdDate;
	
	@Column(name="UPDATED_DATE")
	private Date updatedDate;
	
	@Column(name="STATUS")
	private String status;
	
	@Column(name="MESSAGE_TYPE")
	private String messageType;
	
	@Column(name="ENTITY_ID")
	private String entityId;
	
	@Column(name="MESSAGE_CONTENT")
	private String messageContent;
	
	
	

	public MessageDetailsDb() {
	}

	public MessageDetailsDb(String messageId, String registrationId) {
		this.messageId = messageId;
		this.registrationId = registrationId;
		this.createdDate = new Date();
		this.updatedDate = new Date();
		this.status = GCMNotificationStatus.NOT_DELIVERED.getType();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getMessageType() {
		return messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getMessageContent() {
		return messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public String getEntityId() {
		return entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}
	
}
